name: Run Python Script Daily

on:
  schedule:
    - cron: '50 22 * * *'  # Runs every day at 9 AM UTC
  workflow_dispatch:      # Optional: allows manual run

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      EMAIL_KEY: ${{ secrets.EMAIL_KEY }}
      TWILLO_AUTH_TOKEN: ${{ secrets.TWILLO_AUTH_TOKEN }}
      ACCOUNT_SID: ${{ secrets.ACCOUNT_SID }}
      PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
      ESS_PASSWORD: ${{ secrets.ESS_PASSWORD }}
    # Add all the secrets you need here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_ess.txt

      - name: Run script
        run: python ess_pa_hosted.py
